# Generated by Django 4.2.24 on 2025-09-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_officialsearchapplication_customuser_registry_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialsearchapplication',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('assigned', 'Assigned'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('pending', 'pending')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
